name: Build and Push Docker Image

on:
  schedule:
    - cron: '0 12 * * 1'  # Weekly build (every Monday at 12:00 UTC)
  workflow_dispatch:  # Allow manual trigger

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      packages: write # Required for GHCR
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry (GHCR)
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "$GITHUB_ACTOR" --password-stdin

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/cdevel:latest \
            -f .docker/Dockerfile_alpine .

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/cdevel:latest
